### ISSUE TITLE
Assign the start time 

### ISSUE THREAD

**Issue by oaattia** [hilios/jQuery.countdown#106]
Hello, i like your plugin, great work, how can i assign a start timedate to count down from, as i'm doing a plugin and the js time differ from the server backend time

**Comment by hilios** [comment]
Sorry but for now you can't control the start date!

**Comment by hilios** [comment]
Hi, looking over this issue for 2.0.4 this request is kind of invalid, look how at [line 189](https://github.com/hilios/jQuery.countdown/blob/master/src/countdown.js#L189) I use the `finalDate` that you provide to calculate the offset. At the end of the day we can't run away from `new Date`, because it's its how we get the difference from date.

The problem is, either the user end change his machine date (nothing we can do about it natively) or you can check the timezone, look at [Timezone Aware Example](http://hilios.github.io/jQuery.countdown/examples/timezone-aware.html).
