### ISSUE TITLE
sync to server time

### ISSUE THREAD

**Issue by annadarwin** [hilios/jQuery.countdown#114]
how can i sync timer with server time? 
i tried this plugin and it sync with client time not server time

**Comment by maximski** [comment]
I have the same issue. I would love an alternative time format as a parameter, e.g. passing how much time left till the end of the countdown (so the end time is determined by the server and not by the client) rather than passing the finish datetime itself.

**Comment by hilios** [comment]
:+1:

**Comment by rozulimam** [comment]
how do I want to use a time server , this script that I use , thanks to its support please :(

$('#waktu_terbaru_<?php echo $data['id_voucher'] ?>').countdown('<?php echo $batas_waktu ?> 00:00:00')
.on('update.countdown', function(event) {
$(this).html(event.strftime('%D Hari %H:%M:%S '));})
.on('finish.countdown', function(event) { 
$(this).html('HABIS TERJUAL');});

**Comment by KarlJakober** [comment]
see my pull request right above your post.

**Comment by rozulimam** [comment]
where should I save this script
 '<?= $now->format("M j, Y H:i:s O") ?>' ?

**Comment by KarlJakober** [comment]
you insert that as a 3rd parameter. $now is a datetime object.

**Comment by rozulimam** [comment]
Example I use:

$('#waktu_terbaru_<?php echo $data['id_voucher'] ?>').countdown('<?php echo $batas_waktu ?> 00:00:00')
.on('update.countdown', function(event) {
$(this).html(event.strftime('%D Hari %H:%M:%S '));},'<?= $now->format("M j, Y H:i:s O") ?>')
.on('finish.countdown', function(event) { 
$(this).html('HABIS TERJUAL');});

OR

$('#waktu_terbaru_<?php echo $data['id_voucher'] ?>').countdown('<?php echo $batas_waktu ?> 00:00:00')
.on('update.countdown', function(event) {
$(this).html(event.strftime('%D Hari %H:%M:%S '));})
.on('finish.countdown', function(event) { 
$(this).html('HABIS TERJUAL');},'<?= $now->format("M j, Y H:i:s O") ?>');

because I use update.countdown and finish.countdown..

**Comment by KarlJakober** [comment]
second, please review the changes I made to the code and understand it.

**Comment by hilios** [comment]
Actually version 1.0 works that way, fell free to use it, there is an issue that I explain the historical issue that I changed the way the plugin works, but mainly it's because of precision.
