### ISSUE TITLE
Get time from server

### ISSUE THREAD

**Issue by rozulimam** [hilios/jQuery.countdown#119]
how do I want to use a time server , this script that I use , thanks to its support please :(

$('#waktu_terbaru_<?php echo $data['id_voucher'] ?>').countdown('<?php echo $batas_waktu ?> 00:00:00')
.on('update.countdown', function(event) {
$(this).html(event.strftime('<span class="waktu_warna">%D Hari</span> %H:%M:%S '));})
.on('finish.countdown', function(event) { 
$(this).html('HABIS TERJUAL');});

**Comment by lrdiv** [comment]
:+1: It would be great to specify the current datetime.

**Comment by hilios** [comment]
Guys, what's wrong in making a request to the server, retrieve the date and then reset the countdown according?

```javascript
var $clock = $("#clock").on('update.countdown', function(event) { /* ... */ });
// Sync with the server time
$.get("http://myhost.com/server-time", {}, function(data) {
    var serverTime = new Date(data);
    $clock.countdown(serverTime);
});
```

One could perform this request time to time in a `setInterval` if is so important.

The main issue here is that Javascript date and time rely on the users machine, and this is way beyond this plugin (or any) can solve alone, but you can mitigate it with plain jquery like the example above!

Hope that's help.

BTW: The version 1.x supports counting through an interval rather than date time, but I believe it's a worse approach, but you choose.

**Comment by vietnguyen09** [comment]
I have been trying this, but it's not working. When I change my PC time, count down still effects

**Comment by rozulimam** [comment]
Good job.. thanks bro ^_^

2016-08-30 15:02 GMT+07:00 Johnny Nguyen <notifications@github.com>:
