### ISSUE TITLE
fadeIn of weeks/days/hours etc

### ISSUE THREAD

**Issue by BenLattimore** [hilios/jQuery.countdown#132]
Really great plug-in!

You'll see here (http://counterdown.meteor.com/countdowns/qRiRGGq558x3XSrpc) how I am fading in individual elements on the page. The ideal is to do a similar gradual load to each part of the countdown i.e. weeks loads in first, then days, then hours, then seconds.

However the issue I'm having is that with the following code:

<img width="505" alt="screen shot 2015-07-15 at 13 11 15" src="https://cloud.githubusercontent.com/assets/5930535/8698142/05081c40-2af3-11e5-8815-b2016fe93230.png">

Even if I add classes/ids to the divs within the .timer, the update.countdown (I think) is preventing me from manipulating it - one presumes they are being destroyed and created even millisecond? If you look under Chrome Dev Tools you can see the "blocking."

Am I being really dumb or is there a way to manipulate these divs for the fading in? My sense is that I should try and prevent the "bubbling up" but I'm still rather a newbie and might be looking at the wrong thing.

**Comment by hilios** [comment]
Matter of fact you are doing a very hard thing, but you are going in the right way, I faced the same problem at [the main example of this plugin website](http://hilios.github.io/jQuery.countdown/).

Because of precision, the countdown updates its self every 100ms and dispatches an event in the process. The gotcha is that if try to re-render de html (`$(this).html(...)` perform the action) every time, you don't give time to perform the animation.

So you must compare if the date is the same from the last one, for only then render the html.

Because strings are more easy to compare than object we could create two variables `currDate` and `lastDate`, to hold a countdown string, if the `currDate` is different than the `lastDate` then we execute the render.

This  would allow the animation to perform correctly.

```javascript
var lastDate = '00:00:00:00:00';

$('#clock').countdown('YYYY/MM/DD', function(event) {
  var currDate = event.strftime('%D:%H:%M:%S';);
  if(currDate !== lastDate) {
    lastDate = currDate;
    $(this).html("<span></span>");
  }
});
```

You can follow the code of the example I mentioned above as a guideline:
https://github.com/hilios/jQuery.countdown/blob/gh-pages/_includes/main-example.html

**Comment by hilios** [comment]
Hi there, at the new version (2.0.4) of the plugin the events are only dispatched when are changes on the time! If you have more questions about this feel free to ask and I will re-open this issue.

**Comment by BenLattimore** [comment]
Hey! Just been trying to set this up using the new version (2.05) - the official Meteor package is still at 2.04 so I've just added the downloaded 2.05 files to my client folder.

Unless I've misunderstood/being really stupid, everything is still as it was? There are still update events being dispatched every second that block access to the individual element ie. Day, Hour, Second, even when only the seconds change.

My understanding was that the new version would not update, say, the Day when only second has changed? 

Do I still need to incorporate this code to stop the events being dispatched?

`
var lastDate = '00:00:00:00:00';

$('#clock').countdown('YYYY/MM/DD', function(event) {
  var currDate = event.strftime('%D:%H:%M:%S';);
  if(currDate !== lastDate) {
    lastDate = currDate;
    $(this).html("<span></span>");
  }
});
`

**Comment by hilios** [comment]
Sorry if my previous comment mislead you in someway. You are right, it's still executing the callback at least every second (but opposed with calling every 100ms it's better). 

In the end we gonna have to control which element to render some way, but now I assure that the event is only dispatched when something as changed!

I believe that using ReactJS would be a great to achieve this, because natively does this comparison and only renders the parts of the dom that changed!
