### ISSUE TITLE
exclude certain days

### ISSUE THREAD

**Issue by vmahabir** [hilios/jQuery.countdown#137]
Hi, 

Is it possible to exclude certain days? If so; how?

Thank you :).

**Comment by hilios** [comment]
You could use the `event.offset` properties to apply a custom render rule:

```js
$('#clock').countdown('YYYY-MM-DD', function(event) {
    $this = $(this);
    if (event.offset.totalDays > 20) {
        $this.html("Far, far away... Don't worry!");
    } else {
        $this.html('%-D days %-H h %M min %S sec left');
    }
});
```

More about the properties at: http://hilios.github.io/jQuery.countdown/documentation.html#event-object

**Comment by vmahabir** [comment]
I'm sorry Hillios. I wasn't clear with my question

Im gonna try too explain what I need; I need a counter that counts daily from 19:00 to the next day 16:00 up until Thursday.  
I need to specifically exclude Friday, saturday and Sunday from the counter. It's needs to count from thursday 19:00 to monday 16:00.

**Comment by hilios** [comment]
This is not a plugin question, it's a javascript problem, you can check the [JavaScript Date Object reference at MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay).

```js
if (new Date().getDay() in [1, 2, 3, 5]) {
 // start the countdown
}
```

Your question is more suitable to StackOverflow, because your problem is clearly how to handle the JavaScript not the plugin itself.

Regards

**Comment by vmahabir** [comment]
Hi Hillios, 
Thank you for your advice. I will do that.

Regards!
