### ISSUE TITLE
Events from other sources are passed to callback

### ISSUE THREAD

**Issue by runeborg** [hilios/jQuery.countdown#140]
Events from other sources (for example SignalR events) are coming in to the countdown-callback.

**Comment by hilios** [comment]
This problem is caused by a event name collision with SignalR.

The **countdown** plugin dispatches a `update`, `finish` and `stop` events within the `*.countdown` namespace. Even if you simple trigger the event without it, it will be caught by the handler. Keep in mind that this is the **expected jQuery behaviour!!!**.

The following example the `update.countdown` event **WILL** be dispatched twice:

```js
$('#el').on('update.countdown', function() { /* ... */ });
// Triggers with and without the namespace
$('#el').trigger('update.countdown');
$('#el').trigger('update');
```

To solve this problem you could prevent SignalR bubbling the event to it's siblings or simple check the [event namespace](http://api.jquery.com/event.namespace/):


```js
$('#el').on('update.countdown', function(event) { 
   // Block event triggered without the countdown namespace
   if (e.namespace !== "countdown") return;
});
```

I added a simple test case (0cade6dc6164b14aa4cde286d67caf40f2291e1b) to the test suit and the provided example should work properly.
