### ISSUE TITLE
milliseconds as argument does not work.

### ISSUE THREAD

**Issue by baminc** [hilios/jQuery.countdown#152]
Hey,

just tried the countdown with milliseconds as a end time. Seems not to be working (at least for me).

tried it with this:

```js
$('div.clock').countdown(30*60000, function(event) {
   $(this).html(event.strftime('%M:%S'));
});
```

workaround:
```js
$('div.clock').countdown(new Date(new Date().getTime() + 30*60000), function(event) {
   $(this).html(event.strftime('%M:%S'));
});
```

Torben

**Comment by hilios** [comment]
@baminc the code is working properly, let's take a closer look at the given milliseconds in the first function:

```js
new Date(30*60000)
-> Wed Dec 31 1969 21:30:00 GMT-0300 (BRT)
```

This won't start the default countdown because the given time is in the past, so the it's already finished. Now the latter:

```js
new Date(new Date().getTime() + 30*60000)
-> Wed Oct 14 2015 10:21:34 GMT-0300 (BRT)
```

Much more like it, because the return date is in the future. That is the **default** behavior of the `Date` object in javascript, so the *workaround* is the right way of starting dates:

> Creates a JavaScript Date instance that represents a single moment in time. Date objects are based on a time value that is the number of milliseconds since 1 January, 1970 UTC.

Source: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date

Hope it helped!

**Comment by baminc** [comment]
OK, maybe the documentation confused me here: The final date argument says it could take "The milliseconds" which I thought was just the time until final date (like in if you want 30 Minutes Countdown just put the milliseconds for 30 minutes in there). 

Maybe update the documentation to be more clear, anyway thanks for the heads up!

**Comment by hilios** [comment]
:+1: I will improve it, thanks for the heads up!
