### ISSUE TITLE
Invalid future dates not working on Chrome (but work on Safari and Firefox)

### ISSUE THREAD

**Issue by gmox** [hilios/jQuery.countdown#206]
So if you have a date like 2016/06/35 (2016/06/28 + 7 days), Chrome produces NaN on countdowns while Safari and Firefox produce the correct times (6 days etc).

**Comment by gmox** [comment]
Additionally, it should be noted that Chrome's implementation of Date() does produce the correct date:

     > new Date('2016/06/35')
     < Tue Jul 05 2016 00:00:00 GMT-0400 (EDT) = $2

**Comment by gmox** [comment]
It is also worth noting that while
     new Date('2016/06/35')
throws an Invalid Date error,
     new Date(2016,5,35)
does not, and behaves as expected. This is starting to seem like a Chrome bug, but since it affects jQuery.countdown, I guess you're the first to know.

**Comment by hilios** [comment]
This plugin rely heavily on the native JavaScript `Date` object, it doesn't try to do any magic with it, but only provide a thin layer of functionality to handle countdowns. So there is nothing I can do.

But it seems to me that this is an invalid date, there are several [libraries](http://momentjs.com) to handle date time manipulations, instead of doing this workaround and rely on the browser to behave in such manner use some of this libs.

I assure you that will be more practical than that.
