### ISSUE TITLE
Suggestion for a destroy() method

### ISSUE THREAD

**Issue by thinkdj** [hilios/jQuery.countdown#215]
Facing issues when countdown is called recursively. Can we have a 'destroy' that brings up a clean slate?

**Comment by hilios** [comment]
Try to use the:

```js
$el.countdown('remove');
```

**Comment by thinkdj** [comment]
Thank you! 
Update: Sorry, this does not work as intended.

**Comment by thinkdj** [comment]
I had to call countdown recursively (within finish.countdown; on the same element), and it was causing the code to run as many times as the recursion increased. 
I spent two days behind fixing it, trying out global variables, 'stop', 'remove' et al. 

Finally solved it by the following logic in finish.countdown: 
$el.remove();
$el.parent().append("<span id='countdn'></span>");
$el.countdown();

Maybe it'll help someone else.

**Comment by AnnikaNissen** [comment]
Thanks, @thinkdj! Your "solution" works for me.

@hilios : `$el.countdown('remove');` unfortunately doesn't work. It does something (updates the options to the once given last), but it doesn't kill the "old" countdown entirely. When I do `console.log('update')` in the `update.countdown`-listener, I still get 2 log messages. 

I would really appreciate a clean "destroy" method, so that it is no longer required to use a hack (removing and re-appending the element) when you want to re-initialize a countdown.
