### ISSUE TITLE
Doesn't working in Safari

### ISSUE THREAD

**Issue by lucassonsinlima** [hilios/jQuery.countdown#281]

**Comment by shoreline-chrism** [comment]
I am not sure if anyone is searching for this same issue, but I ran across the same issue.  In Safari on mobile and Chrome for iOS, the date was stuck at zeros.  It turned out the issue I had was, when I was integrating the script into my wordpress site, I was getting a date using PHP, so here's an example:

````php
$date = date('Y-M-d h:i:s a', strtotime( $date . " " . $time ));
````

And then I was using that `$date` variable in the javascript:

````
countDate = new Date("<?php echo $date; ?>"),
````

It turns out that the javascript date object wasn't getting created correctly because it couldn't understand the date format on iOS.  I updated my date format from `Y-M-d h:i:s a` to `D, d M y H:i:s` and then the javascript date object was created correctly.
